FROM ubuntu:bionic
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && DEBIAN_FRONTEND=noninteractive apt-get install --yes \
    tzdata \
    build-essential \
    psmisc \
    net-tools \
    bc \
    tshark \
    iputils-ping \
    iptables \
    vim \
    iperf3 \
    iproute2 \
    libconfig++9v5 \
    libsctp1 \
    pkg-config \
    dh-autoreconf \
    ncurses-dev \
    build-essential \
    libssl-dev \
    libpcap-dev \
    libncurses5-dev \
    libsctp-dev \
    lksctp-tools \
    cmake \
    libprotobuf-dev \
    protobuf-compiler \
    git \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y software-properties-common gcc && \
    add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y python3.6 python3-distutils python3-pip python3-apt
RUN pip3 install numpy

#WORKDIR /
# RUN git clone https://github.com/SIPp/sipp.git
# WORKDIR /sipp
#RUN mkdir build
#WORKDIR /sipp/build
#RUN cmake .. -DUSE_SSL=1 -DUSE_SCTP=1 -DUSE_PCAP=1 -DUSE_GSL=1; make all; make install;

WORKDIR /
COPY ./docker/udpserverclient /udpserverclient
COPY ./docker/processedin.txt .
COPY ./docker/processedout.txt .

# expose ports
EXPOSE 80/tcp 9090/tcp 38412/sctp

CMD ["sleep", "infinity"]
